"""
fidelity/level1_cfd.py
----------------------
Level 1 — 2-D RANS Section CFD Evaluator

Implements the pipeline for 2-D CFD evaluation of a wing cross-section.
Supports SU2 (primary) and OpenFOAM (secondary) as solver backends.

Pipeline
--------
1. Export airfoil coordinates to solver-compatible format
2. Generate mesh (Gmsh structured C-mesh or snappyHexMesh)
3. Write solver configuration from template
4. Execute solver (subprocess, async-capable)
5. Parse residuals + force history
6. Return FidelityResult with Cl, Cd and section-level data

When a real solver is not available, the evaluator runs in STUB mode:
it returns a clearly-labelled result with status=stub so downstream code
can detect un-run CFD cases rather than silently consuming zeros.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from fidelity.base import FidelityEvaluator, FidelityLevel, FidelityResult

# ── Config ────────────────────────────────────────────────────────────────────
_SU2_BIN        = os.environ.get("SU2_BIN",        "SU2_CFD")
_GMSH_BIN       = os.environ.get("GMSH_BIN",       "gmsh")
_CFD_WORK_DIR   = Path(os.environ.get("CFD_WORK_DIR", "/tmp/wingopt_cfd"))
_CFD_WORK_DIR.mkdir(parents=True, exist_ok=True)

# Nominal uncertainty for converged 2-D RANS on a well-resolved mesh
_L1_CL_UNCERTAINTY = 0.07   # ±7% 1-sigma
_L1_CD_UNCERTAINTY = 0.10   # ±10%


# ── SU2 configuration template (incompressible RANS, SA turbulence model) ─────
_SU2_TEMPLATE = """\
% WingOpt Level-1 2D CFD — auto-generated by level1_cfd.py
% Design: {design_id}
% AoA: {aoa_deg} deg  |  Re: {Re:.0f}

SOLVER= INC_RANS
KIND_TURB_MODEL= SA
MATH_PROBLEM= DIRECT
RESTART_SOL= NO

INC_DENSITY_INIT= 1.225
INC_VELOCITY_INIT= ( {Vinf:.4f}, 0.0, 0.0 )
INC_ENERGY_EQUATION= NO

AOA= {aoa_deg}
SIDESLIP_ANGLE= 0.0

MACH_NUMBER= {mach:.5f}
REYNOLDS_NUMBER= {Re:.0f}
REYNOLDS_LENGTH= 1.0

MESH_FILENAME= mesh_{design_id}.su2
MESH_FORMAT= SU2

MARKER_EULER= ( airfoil )
MARKER_FAR= ( farfield )
MARKER_PLOTTING= ( airfoil )
MARKER_MONITORING= ( airfoil )

NUM_METHOD_GRAD= WEIGHTED_LEAST_SQUARES
CFL_NUMBER= 50.0
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.1, 2.0, 50.0, 1e6, 0.001 )

CONV_RESIDUAL_MINVAL= -8
CONV_STARTITER= 25
CONV_CAUCHY_ELEMS= 100
CONV_CAUCHY_EPS= 1e-6

ITER= {max_iter}

LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ILU_FILL_IN= 0
LINEAR_SOLVER_ERROR= 1E-10
LINEAR_SOLVER_ITER= 20

OUTPUT_WRT_FREQ= 50
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF )
VOLUME_OUTPUT= ( COORDINATES, SOLUTION, PRIMITIVE )

OUTPUT_FILES= ( RESTART, SURFACE_CSV )
SOLUTION_FILENAME= solution_{design_id}
RESTART_FILENAME= restart_{design_id}
SURFACE_FILENAME= surface_{design_id}
CONV_FILENAME= history_{design_id}
"""

# ── Gmsh C-mesh script template ───────────────────────────────────────────────
_GMSH_TEMPLATE = """\
// WingOpt Level-1 C-mesh — auto-generated
// Airfoil points imported from: {coord_file}
SetFactory("OpenCASCADE");
Merge "{coord_file}";
// Farfield radius: 20 chords
// Wake length:    30 chords
// Wall spacing:   1e-5 c (y+ ~1 at Re={Re:.0f})
// This script requires manual completion with your local Gmsh setup.
// See docs/cfd_setup.md for complete meshing instructions.
"""


@dataclass
class CFDRunRecord:
    """Metadata for a single CFD case."""
    run_id:       str
    design_id:    str
    design_params: Dict[str, float]
    condition:    Dict[str, float]
    case_dir:     Path
    solver:       str
    status:       str = "pending"   # pending | running | done | failed | stub
    Cl:           Optional[float] = None
    Cd:           Optional[float] = None
    Cm:           Optional[float] = None
    residual_min: Optional[float] = None
    wall_time_s:  float = 0.0
    notes:        List[str] = field(default_factory=list)


class Level1Evaluator(FidelityEvaluator):
    """
    2-D RANS Section CFD evaluator (Level 1).

    Parameters
    ----------
    solver : "su2" | "openfoam"
    max_iter : int   — solver iteration limit
    stub_mode : bool — if True, skip actual solver and return stub result
                       (use when SU2/gmsh not installed)
    """

    level = FidelityLevel.LEVEL_1_CFD_2D

    def __init__(
        self,
        solver:   str = "su2",
        max_iter: int = 2000,
        stub_mode: Optional[bool] = None,
    ) -> None:
        self.solver    = solver.lower()
        self.max_iter  = max_iter
        # Auto-detect stub mode if not forced
        self._stub = stub_mode if stub_mode is not None else not self._solver_available()

    # ── Public interface ───────────────────────────────────────────────────────

    def evaluate(
        self,
        design_params: Dict[str, float],
        condition: Optional[Dict[str, float]] = None,
    ) -> FidelityResult:
        result  = self._base_result(design_params, condition)
        cond    = condition or {}
        run_id  = str(uuid.uuid4())[:8]
        t0      = time.perf_counter()

        if self._stub:
            return self._stub_result(result, run_id)

        try:
            case_dir = self._build_case(design_params, cond, run_id)
            record   = self._run_solver(case_dir, design_params, cond, run_id)
            result   = self._pack_result(result, record)
        except Exception as exc:
            result.converged   = False
            result.trust_label = "failed"
            result.confidence  = 0.0
            result.notes.append(f"Level 1 CFD error: {exc}")

        result.solver_time_s = time.perf_counter() - t0
        result.run_id        = run_id
        return result

    def build_case_only(
        self,
        design_params: Dict[str, float],
        condition: Optional[Dict[str, float]] = None,
    ) -> Path:
        """
        Generate the CFD case directory without running the solver.
        Useful for inspecting inputs or submitting to a cluster.
        """
        run_id = str(uuid.uuid4())[:8]
        return self._build_case(design_params, condition or {}, run_id)

    # ── Internal methods ───────────────────────────────────────────────────────

    def _solver_available(self) -> bool:
        try:
            subprocess.run([_SU2_BIN, "--version"], capture_output=True, timeout=5)
            return True
        except Exception:
            return False

    def _build_case(
        self,
        params: Dict[str, float],
        cond:   Dict[str, float],
        run_id: str,
    ) -> Path:
        """Build a complete CFD case directory."""
        from geometry.naca_generator import generate_airfoil

        aoa       = cond.get("aoa_deg",      params.get("aoa_deg", -5.0))
        velocity  = cond.get("velocity_ms",  41.67)
        Re        = cond.get("Re",           712_000)
        mach      = velocity / 340.0   # ISA sea-level speed of sound

        case_dir = _CFD_WORK_DIR / f"l1_{run_id}"
        case_dir.mkdir(parents=True, exist_ok=True)

        # 1. Export airfoil coordinates
        geo      = generate_airfoil(params)
        coord_file = case_dir / "airfoil.dat"
        self._write_coords(geo, coord_file)

        # 2. Write Gmsh mesh script
        gmsh_script = _GMSH_TEMPLATE.format(
            coord_file=str(coord_file), Re=Re
        )
        (case_dir / "mesh.geo").write_text(gmsh_script)

        # 3. Write SU2 config
        cfg = _SU2_TEMPLATE.format(
            design_id=run_id,
            aoa_deg=aoa,
            Vinf=velocity,
            Re=Re,
            mach=mach,
            max_iter=self.max_iter,
        )
        (case_dir / f"wingopt_{run_id}.cfg").write_text(cfg)

        # 4. Write metadata JSON
        meta = {
            "run_id":       run_id,
            "fidelity":     "level1_cfd_2d",
            "solver":       self.solver,
            "design_params": params,
            "condition":    cond,
            "aoa_deg":      aoa,
            "Re":           Re,
            "velocity_ms":  velocity,
        }
        (case_dir / "meta.json").write_text(json.dumps(meta, indent=2))

        return case_dir

    def _write_coords(self, geo: Any, path: Path) -> None:
        """Write Selig-format airfoil coordinate file."""
        lines = [geo.get("name", "WingOpt_airfoil") + "\n"]
        xu, yu = geo["x_upper"], geo["y_upper"]
        xl, yl = geo["x_lower"], geo["y_lower"]
        # Upper surface LE→TE
        for x, y in zip(xu, yu):
            lines.append(f"  {x:.6f}  {y:.6f}\n")
        # Lower surface TE→LE
        for x, y in zip(reversed(xl), reversed(yl)):
            lines.append(f"  {x:.6f}  {y:.6f}\n")
        path.write_text("".join(lines))

    def _run_solver(
        self,
        case_dir: Path,
        params:   Dict[str, float],
        cond:     Dict[str, float],
        run_id:   str,
    ) -> CFDRunRecord:
        """Execute SU2 solver (blocking). Returns run record."""
        cfg_file = next(case_dir.glob("*.cfg"))
        record   = CFDRunRecord(
            run_id=run_id, design_id=run_id,
            design_params=params, condition=cond,
            case_dir=case_dir, solver=self.solver,
        )

        log_path = case_dir / "solver.log"
        try:
            t0  = time.perf_counter()
            ret = subprocess.run(
                [_SU2_BIN, str(cfg_file)],
                cwd=str(case_dir),
                capture_output=True, text=True,
                timeout=3600,
            )
            record.wall_time_s = time.perf_counter() - t0
            log_path.write_text(ret.stdout + "\n" + ret.stderr)

            if ret.returncode != 0:
                record.status = "failed"
                record.notes.append(f"SU2 exit code {ret.returncode}")
            else:
                record.status = "done"
                self._parse_history(case_dir, run_id, record)
        except subprocess.TimeoutExpired:
            record.status = "failed"
            record.notes.append("Solver timeout (>3600 s)")

        return record

    def _parse_history(
        self, case_dir: Path, run_id: str, record: CFDRunRecord
    ) -> None:
        """Parse SU2 history CSV for Cl, Cd, residual."""
        hist_file = case_dir / f"history_{run_id}.csv"
        if not hist_file.exists():
            record.notes.append("History file not found — parsing skipped.")
            return
        try:
            import csv
            rows = []
            with open(hist_file) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    rows.append(row)
            if not rows:
                return
            last = rows[-1]
            # SU2 column names vary by version; try common names
            for cl_key in ("CL", "Cl", "C_Lift"):
                if cl_key in last:
                    record.Cl = float(last[cl_key])
                    break
            for cd_key in ("CD", "Cd", "C_Drag"):
                if cd_key in last:
                    record.Cd = float(last[cd_key])
                    break
            for cm_key in ("CMz", "Cm", "C_Moment_Z"):
                if cm_key in last:
                    record.Cm = float(last[cm_key])
                    break
            for res_key in ("Res_Flow[0]", "rms[Rho]", "Residual_Flow[0]"):
                if res_key in last:
                    record.residual_min = float(last[res_key])
                    break
        except Exception as exc:
            record.notes.append(f"History parse error: {exc}")

    def _pack_result(
        self, result: FidelityResult, record: CFDRunRecord
    ) -> FidelityResult:
        """Populate FidelityResult from a completed CFDRunRecord."""
        result.Cl          = record.Cl
        result.Cd          = record.Cd
        result.Cm          = record.Cm
        result.converged   = record.status == "done" and record.Cl is not None
        result.artifact_dir = str(record.case_dir)

        if result.Cl is not None:
            result.Cl_uncertainty = abs(result.Cl) * _L1_CL_UNCERTAINTY
        if result.Cd is not None:
            result.Cd_uncertainty = abs(result.Cd) * _L1_CD_UNCERTAINTY

        # Derived
        if result.Cl and result.Cd:
            result.Cl_Cd       = result.Cl / result.Cd
            result.efficiency  = abs(result.Cl) / result.Cd if result.Cd > 0 else None

        converged_residual = (
            record.residual_min is not None and record.residual_min < -6
        )
        result.confidence  = 0.88 if (result.converged and converged_residual) else 0.65
        result.trust_label = "high" if result.confidence >= 0.80 else "moderate"

        result.notes.append(
            "Level 1 — 2-D RANS section CFD. "
            f"Solver: {self.solver.upper()}, iterations: {self.max_iter}."
        )
        result.notes.extend(record.notes)
        return result

    def _stub_result(self, result: FidelityResult, run_id: str) -> FidelityResult:
        """
        Return a clearly-labelled stub when the solver is not installed.
        Downstream code must check result.trust_label == 'stub' before use.
        """
        result.converged   = False
        result.confidence  = 0.0
        result.trust_label = "stub"
        result.run_id      = run_id
        result.notes.append(
            "Level 1 CFD not executed — solver not installed (stub mode). "
            "Install SU2 and set SU2_BIN env var to enable real CFD runs. "
            "See docs/cfd_setup.md for instructions."
        )
        return result
