"""
fidelity/level2_cfd.py
----------------------
Level 2 — 3-D Full-Wing RANS CFD Evaluator

Truth layer for design validation. Implements the workflow for submitting
and monitoring a full 3-D RANS simulation of the assembled wing geometry
(mainplane + flap + endplates).

Pipeline
--------
1. Export multi-element 3-D geometry (STL / IGES / OpenFOAM blockMesh)
2. Generate mesh (snappyHexMesh or Gmsh extrusion)
3. Write OpenFOAM or SU2-3D case from template
4. Submit (local subprocess or HPC via ssh/sbatch hook)
5. Poll for convergence / completion
6. Parse integrated forces + moment from postProcessing/
7. Return FidelityResult with full 3-D aerodynamic data

When a real solver is not present the evaluator runs in STUB mode.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from fidelity.base import FidelityEvaluator, FidelityLevel, FidelityResult

# ── Environment config ────────────────────────────────────────────────────────
_OF_BIN         = os.environ.get("OPENFOAM_BIN", "simpleFoam")
_CFD3D_WORK_DIR = Path(os.environ.get("CFD3D_WORK_DIR", "/tmp/wingopt_cfd3d"))
_CFD3D_WORK_DIR.mkdir(parents=True, exist_ok=True)

_L2_CL_UNCERTAINTY = 0.04   # ±4% for converged 3-D RANS on fine mesh
_L2_CD_UNCERTAINTY = 0.06   # ±6%


# ── OpenFOAM simpleFoam controlDict template ──────────────────────────────────
_OF_CONTROL_DICT = """\
/*  WingOpt Level-2 3D CFD — auto-generated by level2_cfd.py
    Design: {design_id}  |  AoA: {aoa_deg}°  |  Re: {Re:.0f}
    Solver: simpleFoam (steady RANS, k-omega SST)
*/
FoamFile {{ version 2.0; format ascii; class dictionary; location "system"; object controlDict; }}

application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {n_iter};
deltaT          1;
writeControl    timeStep;
writeInterval   {write_every};
purgeWrite      3;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   1;
        log             yes;
        patches         (wing flap endplate_left endplate_right);
        rhoInf          1.225;
        Aref            {Aref:.4f};
        lRef            1.0;
        magUInf         {Vinf:.4f};
        CofR            (0.25 0.0 0.0);
        liftDir         (0 1 0);
        dragDir         ({cos_aoa:.6f} {sin_aoa:.6f} 0);
        pitchAxis       (0 0 1);
    }}
    residuals
    {{
        type            residuals;
        libs            (utilityFunctionObjects);
        fields          (p U k omega);
    }}
}}
"""

_OF_FVSCHEMES = """\
FoamFile {{ version 2.0; format ascii; class dictionary; location "system"; object fvSchemes; }}
ddtSchemes      {{ default steadyState; }}
gradSchemes     {{ default Gauss linear; grad(p) Gauss linear; }}
divSchemes
{{
    default                     none;
    div(phi,U)                  Gauss linearUpwindV grad(U);
    div(phi,k)                  Gauss upwind;
    div(phi,omega)              Gauss upwind;
    div((nuEff*dev2(T(grad(U)))) Gauss linear;
}}
laplacianSchemes {{ default Gauss linear corrected; }}
interpolationSchemes {{ default linear; }}
snGradSchemes {{ default corrected; }}
"""

_OF_FVSOLUTION = """\
FoamFile {{ version 2.0; format ascii; class dictionary; location "system"; object fvSolution; }}
solvers
{{
    p        {{ solver GAMG; tolerance 1e-8; relTol 0.01; smoother GaussSeidel; }}
    U        {{ solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }}
    k        {{ solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }}
    omega    {{ solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; }}
}}
SIMPLE
{{
    nNonOrthogonalCorrectors 2;
    residualControl {{ p 1e-5; U 1e-5; k 1e-5; omega 1e-5; }}
}}
relaxationFactors {{ fields {{ p 0.3; }} equations {{ U 0.7; k 0.7; omega 0.7; }} }}
"""


@dataclass
class CFD3DRunRecord:
    run_id:        str
    design_id:     str
    design_params: Dict[str, float]
    condition:     Dict[str, float]
    case_dir:      Path
    status:        str = "pending"   # pending | submitted | running | done | failed | stub
    Cl:            Optional[float] = None
    Cd:            Optional[float] = None
    Cm:            Optional[float] = None
    Cs:            Optional[float] = None   # side force coefficient
    COP_x:         Optional[float] = None   # centre-of-pressure x/c
    residual_p:    Optional[float] = None
    wall_time_s:   float = 0.0
    notes:         List[str] = field(default_factory=list)


class Level2Evaluator(FidelityEvaluator):
    """
    3-D Full-Wing RANS CFD evaluator (Level 2).

    Parameters
    ----------
    solver        : "openfoam" | "su2_3d"
    n_iter        : RANS iteration count (steady)
    stub_mode     : if True, return stub without running solver
    hpc_submit_cmd: optional sbatch / qsub command for HPC submission
    """

    level = FidelityLevel.LEVEL_2_CFD_3D

    def __init__(
        self,
        solver:          str = "openfoam",
        n_iter:          int = 2000,
        stub_mode:       Optional[bool] = None,
        hpc_submit_cmd:  Optional[str] = None,
    ) -> None:
        self.solver         = solver.lower()
        self.n_iter         = n_iter
        self.hpc_submit_cmd = hpc_submit_cmd
        self._stub = stub_mode if stub_mode is not None else not self._solver_available()

    # ── Public interface ───────────────────────────────────────────────────────

    def evaluate(
        self,
        design_params: Dict[str, float],
        condition: Optional[Dict[str, float]] = None,
    ) -> FidelityResult:
        result = self._base_result(design_params, condition)
        cond   = condition or {}
        run_id = str(uuid.uuid4())[:8]
        t0     = time.perf_counter()

        if self._stub:
            return self._stub_result(result, run_id)

        try:
            case_dir = self._build_case(design_params, cond, run_id)
            record   = self._run_solver(case_dir, design_params, cond, run_id)
            result   = self._pack_result(result, record)
        except Exception as exc:
            result.converged   = False
            result.trust_label = "failed"
            result.confidence  = 0.0
            result.notes.append(f"Level 2 CFD error: {exc}")

        result.solver_time_s = time.perf_counter() - t0
        result.run_id        = run_id
        return result

    def build_case_only(
        self,
        design_params: Dict[str, float],
        condition: Optional[Dict[str, float]] = None,
    ) -> Path:
        run_id = str(uuid.uuid4())[:8]
        return self._build_case(design_params, condition or {}, run_id)

    def submit_hpc(
        self,
        design_params: Dict[str, float],
        condition: Optional[Dict[str, float]] = None,
    ) -> Dict[str, str]:
        """
        Build the case and submit via HPC job scheduler.
        Returns {'run_id': ..., 'job_id': ..., 'case_dir': ...}.
        """
        cond    = condition or {}
        run_id  = str(uuid.uuid4())[:8]
        case_dir = self._build_case(design_params, cond, run_id)

        if not self.hpc_submit_cmd:
            return {"run_id": run_id, "status": "case_built_no_submit", "case_dir": str(case_dir)}

        try:
            cmd    = self.hpc_submit_cmd.split() + [str(case_dir / "submit.sh")]
            ret    = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            job_id = ret.stdout.strip().split()[-1] if ret.returncode == 0 else "unknown"
            return {"run_id": run_id, "job_id": job_id, "case_dir": str(case_dir), "status": "submitted"}
        except Exception as exc:
            return {"run_id": run_id, "error": str(exc), "case_dir": str(case_dir), "status": "submit_failed"}

    # ── Case building ──────────────────────────────────────────────────────────

    def _build_case(
        self,
        params: Dict[str, float],
        cond:   Dict[str, float],
        run_id: str,
    ) -> Path:
        import math
        aoa      = cond.get("aoa_deg", params.get("aoa_deg", -5.0))
        velocity = cond.get("velocity_ms", 41.67)
        Re       = cond.get("Re", 712_000)
        span     = params.get("aspect_ratio", 3.5)   # aspect ratio as proxy for span
        Aref     = span * 1.0   # plan area for coefficients (span × chord=1)
        cos_aoa  = math.cos(math.radians(-aoa))
        sin_aoa  = math.sin(math.radians(-aoa))

        case_dir = _CFD3D_WORK_DIR / f"l2_{run_id}"
        for sub in ("0", "constant", "system", "postProcessing"):
            (case_dir / sub).mkdir(parents=True, exist_ok=True)

        # system/controlDict
        (case_dir / "system" / "controlDict").write_text(
            _OF_CONTROL_DICT.format(
                design_id=run_id, aoa_deg=aoa, Re=Re,
                n_iter=self.n_iter, write_every=max(50, self.n_iter // 20),
                Aref=Aref, Vinf=velocity, cos_aoa=cos_aoa, sin_aoa=sin_aoa,
            )
        )
        (case_dir / "system" / "fvSchemes").write_text(_OF_FVSCHEMES)
        (case_dir / "system" / "fvSolution").write_text(_OF_FVSOLUTION)

        # Geometry export hook — writes STL of wing assembly
        self._export_geometry(params, case_dir)

        # HPC submission script
        submit_sh = (
            f"#!/bin/bash\n"
            f"#SBATCH --job-name=wingopt_{run_id}\n"
            f"#SBATCH --ntasks=16\n"
            f"#SBATCH --time=04:00:00\n"
            f"cd {case_dir}\n"
            f"blockMesh && snappyHexMesh -overwrite && {_OF_BIN} > log.simpleFoam 2>&1\n"
        )
        (case_dir / "submit.sh").write_text(submit_sh)

        # Metadata
        meta = {
            "run_id": run_id, "fidelity": "level2_cfd_3d",
            "solver": self.solver, "design_params": params,
            "condition": cond, "n_iter": self.n_iter,
        }
        (case_dir / "meta.json").write_text(json.dumps(meta, indent=2))
        return case_dir

    def _export_geometry(self, params: Dict[str, float], case_dir: Path) -> None:
        """
        Export 3-D wing geometry for meshing.
        Currently writes a geometry README + placeholder STL.
        Full 3-D CAD export requires integration with geometry/multi_element.py.
        """
        readme = (
            "# WingOpt Level-2 Geometry Export\n\n"
            "Geometry parameters:\n"
            + "\n".join(f"  {k}: {v}" for k, v in params.items())
            + "\n\nTo generate full 3-D geometry:\n"
            "  python -m geometry.multi_element --params '...' --output constant/triSurface/\n\n"
            "Required surfaces:\n"
            "  wing.stl         — mainplane\n"
            "  flap.stl         — trailing-edge flap\n"
            "  endplate_left.stl\n"
            "  endplate_right.stl\n"
        )
        (case_dir / "constant" / "geometry_README.md").write_text(readme)

        # Placeholder STL (real generation in multi_element.py)
        stl_placeholder = (
            "solid wing_placeholder\n"
            "  # Replace with actual geometry from geometry/multi_element.py\n"
            "endsolid wing_placeholder\n"
        )
        tri = case_dir / "constant" / "triSurface"
        tri.mkdir(exist_ok=True)
        (tri / "wing.stl").write_text(stl_placeholder)

    # ── Solver execution ───────────────────────────────────────────────────────

    def _solver_available(self) -> bool:
        try:
            subprocess.run([_OF_BIN, "-help"], capture_output=True, timeout=5)
            return True
        except Exception:
            return False

    def _run_solver(
        self,
        case_dir: Path,
        params:   Dict[str, float],
        cond:     Dict[str, float],
        run_id:   str,
    ) -> CFD3DRunRecord:
        record = CFD3DRunRecord(
            run_id=run_id, design_id=run_id,
            design_params=params, condition=cond,
            case_dir=case_dir,
        )
        t0 = time.perf_counter()
        try:
            # blockMesh + simpleFoam
            for cmd in [["blockMesh"], [_OF_BIN]]:
                ret = subprocess.run(
                    cmd, cwd=str(case_dir),
                    capture_output=True, text=True, timeout=7200
                )
                if ret.returncode != 0:
                    record.status = "failed"
                    record.notes.append(f"{cmd[0]} failed: {ret.stderr[:200]}")
                    return record
            record.status     = "done"
            record.wall_time_s = time.perf_counter() - t0
            self._parse_forces(case_dir, record)
        except subprocess.TimeoutExpired:
            record.status = "failed"
            record.notes.append("Solver timeout (>7200 s)")
        return record

    def _parse_forces(self, case_dir: Path, record: CFD3DRunRecord) -> None:
        """Parse OpenFOAM postProcessing/forceCoeffs for Cl, Cd, Cm."""
        fc_dirs = list((case_dir / "postProcessing" / "forceCoeffs").glob("*"))
        if not fc_dirs:
            record.notes.append("forceCoeffs postProcessing not found.")
            return
        fc_file = sorted(fc_dirs)[-1] / "coefficient.dat"
        if not fc_file.exists():
            fc_file = sorted(fc_dirs)[-1] / "forceCoeffs.dat"
        if not fc_file.exists():
            record.notes.append("Force coefficient file not found.")
            return
        try:
            lines = fc_file.read_text().splitlines()
            # Last non-comment line: Time Cm Cd Cl Cl(f) Cl(r)
            for line in reversed(lines):
                if line.strip() and not line.startswith("#"):
                    parts = line.split()
                    if len(parts) >= 4:
                        record.Cm = float(parts[1])
                        record.Cd = float(parts[2])
                        record.Cl = float(parts[3])
                    break
        except Exception as exc:
            record.notes.append(f"Force parse error: {exc}")

    def _pack_result(
        self, result: FidelityResult, record: CFD3DRunRecord
    ) -> FidelityResult:
        result.Cl           = record.Cl
        result.Cd           = record.Cd
        result.Cm           = record.Cm
        result.converged    = record.status == "done" and record.Cl is not None
        result.artifact_dir = str(record.case_dir)

        if result.Cl and result.Cd:
            result.Cl_Cd      = result.Cl / result.Cd
            result.efficiency = abs(result.Cl) / result.Cd if result.Cd > 0 else None

        if result.Cl is not None:
            result.Cl_uncertainty = abs(result.Cl) * _L2_CL_UNCERTAINTY
        if result.Cd is not None:
            result.Cd_uncertainty = abs(result.Cd) * _L2_CD_UNCERTAINTY

        result.confidence  = 0.95 if result.converged else 0.0
        result.trust_label = "high" if result.converged else "failed"
        result.notes.append(
            f"Level 2 — 3-D RANS CFD. Solver: {self.solver.upper()}, "
            f"iterations: {self.n_iter}. Wall time: {record.wall_time_s:.0f} s."
        )
        result.notes.extend(record.notes)
        return result

    def _stub_result(self, result: FidelityResult, run_id: str) -> FidelityResult:
        result.converged   = False
        result.confidence  = 0.0
        result.trust_label = "stub"
        result.run_id      = run_id
        result.notes.append(
            "Level 2 CFD not executed — solver not installed (stub mode). "
            "Install OpenFOAM and set OPENFOAM_BIN env var to enable 3-D RANS runs. "
            "See docs/cfd_setup.md for setup instructions."
        )
        return result
